version: "3"
services:
  server:
    build: .
    ports:
      - 80:8080
    links:
      - database
    environment:
      DB_USER: postgres
      DB_PWD: 123456
      DB_HOST: database
      DB_PORT: 5432
  database:
    image: postgres:10.17
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=invent"
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: